# - name: attach volumes
#   openstack.cloud.server_volume:
#     state: present
#     volume: "{{inventory_hostname}}"
#     server: "{{inventory_hostname}}"
#     device: /dev/vdb

- name: create filesystem
  community.general.filesystem:
    dev: /dev/vdb
    fstype: ext4
  become: yes

- name: mount volumes
  ansible.posix.mount:
    path: /mnt/data
    src: /dev/vdb
    fstype: ext4
    state: "mounted"
  become: yes

- name: give rw permissions to mounted volume
  ansible.builtin.command:
    cmd: chmod 777 -R /mnt/data
  become: yes