#https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/
services:
  web:
    build: ./services/flask
    command: gunicorn --bind 0.0.0.0:5000 server:app
    expose:
      - 5000
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - web
  assets:
    build: ./services/asset-server
    ports:
      - 8081:8081
    volumes:
      - ./assets:/app