# Team 13: Alex Wang 1427869, Ka Shun Carson Young 1086178, Eldon Yeh 1276574, Yukash Sivaraj 1054297
services:
  frontend:
    build: ./
    restart: "always"
    network_mode: "host"
    container_name: frontend