- name: apt install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: yes

- name: pip install docker
  ansible.builtin.pip:
    name: 
      - docker

- name: Create harvester directory
  ansible.builtin.file:
    path: ~/harvester
    state: directory

- name: Copy script files
  ansible.builtin.copy:
    src: script
    dest: ~/
    mode: '0644'

- name: Build the harvester image
  community.docker.docker_image:
    build:
      path: ~/harvester
    name: harvester
    source: build
    debug: true
    force_source: true