#!/bin/bash
curl -XPOST "http://${user}:${pass}@${masternode}:5984/_cluster_setup" \
    --header "Content-Type: application/json"\
    --data "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\
            \"username\": \"${user}\", \"password\":\"${pass}\", \"port\": \"5984\",\
            \"remote_node\": \"${node}\", \"node_count\": \"2\",\
            \"remote_current_user\":\"${user}\", \"remote_current_password\":\"${pass}\"}"


curl -XPOST "http://${user}:${pass}@${masternode}:5984/_cluster_setup"\
    --header "Content-Type: application/json"\
    --data "{\"action\": \"add_node\", \"host\":\"${node}\",\
            \"port\": \"5984\", \"username\": \"${user}\", \"password\":\"${pass}\"}"

curl -XPOST "http://${user}:${pass}@${masternode}:5984/_cluster_setup"\
    --header "Content-Type: application/json" --data "{\"action\": \"finish_cluster\"}"