# Team 13: Alex Wang 1427869, Ka Shun Carson Young 1086178, Eldon Yeh 1276574, Yukash Sivaraj 1054297
version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    network_mode: "host"
    container_name: db
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
      - NODENAME=${node}
    volumes:
        - /mnt/data/dbdata:/opt/couchdb/data