version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    network_mode: "host"
    container_name: db
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
        - ./dbdata:/opt/couchdb/data