# Team 13: Alex Wang 1427869, Ka Shun Carson Young 1086178, Eldon Yeh 1276574, Yukash Sivaraj 1054297
---
- hosts: database
  tasks:
    - name: Stop couchdb on all nodes
      community.docker.docker_compose:
        project_src: ~/couchdb
        state: absent
      environment:
        node: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
        masternode: 172.26.131.88