# Team 13: Alex Wang 1427869, Ka Shun Carson Young 1086178, Eldon Yeh 1276574, Yukash Sivaraj 1054297
- name: Install required system packages
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker-ce and docker-compose
  become: true
  apt:
    name: 
      - docker-ce
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add the user ubuntu to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes
  become: yes