# Team 13: Alex Wang 1427869, Ka Shun Carson Young 1086178, Eldon Yeh 1276574, Yukash Sivaraj 1054297
FROM python:latest
WORKDIR /app

COPY . ./
RUN pip install -r requirements.txt
#ENTRYPOINT ["python3", "server.py"]
